---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7.1
  - name: debian-7.8
  - name: debian-8.1

suites:
  - name: firefox_test
    run_list:
      - recipe[firefox_test::default]
      - recipe[firefox_test::version]
      - recipe[firefox_test::x11]
    attributes:

  - name: firefox_custom_version_test
    run_list:
      - recipe[firefox_test::default]
    attributes: { firefox: { version: "28.0+build2-0ubuntu2" } }
    excludes:
      - ubuntu-12.04
      - centos-6.7
      - centos-7.1
      - debian-7.8
      - debian-8.1
